<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Language</name>
   <tag></tag>
   <elementGuidId>c884f481-c11a-4ba8-a0a0-74c029fe6454</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/main/div[2]/div/div/div/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select.language-select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eff7b965-1641-4cc0-8123-aaaba1ddc2e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>language-select</value>
      <webElementGuid>1f15ee92-bdf0-42c6-be38-5ecd9786df55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>C++PythonJavaScript</value>
      <webElementGuid>613cee24-704c-4830-ba70-ffad70fbe9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;interface-code-wrapper full-interface-container&quot;]/div[@class=&quot;problem-container&quot;]/main[@class=&quot;main-content&quot;]/div[@class=&quot;code-editor-and-console&quot;]/div[@class=&quot;code-area&quot;]/div[@class=&quot;code-editor&quot;]/div[@class=&quot;code-header&quot;]/select[@class=&quot;language-select&quot;]</value>
      <webElementGuid>1f37dc3a-6bc0-4f90-9d7d-57f715ccb725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/main/div[2]/div/div/div/select</value>
      <webElementGuid>de4ed711-3048-4861-8681-7842a063b6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only one valid answer exists.'])[1]/following::select[1]</value>
      <webElementGuid>7c59389b-68e3-494a-8dc1-7f932ca7b314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Constraints:'])[1]/following::select[1]</value>
      <webElementGuid>b5eda71b-ba30-409e-868f-7689d450f21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⚙️'])[1]/preceding::select[1]</value>
      <webElementGuid>d67117e3-105b-45d7-9201-474ba38d9ad1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>76dadf25-51d9-4e19-93f1-fae36d26f5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'C++PythonJavaScript' or . = 'C++PythonJavaScript')]</value>
      <webElementGuid>640524c8-3d55-4c4e-9d9c-f775293da491</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
