ALTER TABLE users ADD COLUMN IF NOT EXISTS github_link VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS linkedin_link VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS theme_preference VARCHAR(50) DEFAULT 'light';
ALTER TABLE users ADD COLUMN IF NOT EXISTS full_name VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;